### ISSUE TITLE
How to train the model?

### ISSUE THREAD

**Issue by zhu2bowen** [ChristophReich1996/Differentiable_JPEG_Shin#1]
Thans for your work.But, how to train the model if take it as a nn.module?

**Comment by ChristophReich1996** [comment]
The model does not include learnable parameters (at the moment) so you can't learn anything as JPEG is not a learned function. However, you can, for instance, make the color conversation parameters learnable and learn them w.r.t. whatever loss you desire. Hope this helps!

**Comment by zhu2bowen** [comment]
@ChristophReich1996  Consider the scene: I have two images, one is HR and anoter is LR, I want to train the JPEG model to get suitable param "compression strength" so that I can trans HR to LR。I want to use L1 loss。What can I do？Thanks !!!
